<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="104201" started-at="2020-10-23T11:46:39Z" finished-at="2020-10-23T11:48:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="104201" started-at="2020-10-23T11:46:39Z" finished-at="2020-10-23T11:48:23Z">
      <class name="practise.AppiumFramework.ECommerceTestCase_4">
        <test-method status="PASS" signature="init()[pri:0, instance:practise.AppiumFramework.ECommerceTestCase_4@65e2dbf3]" name="init" is-config="true" duration-ms="104057" started-at="2020-10-23T11:46:39Z" finished-at="2020-10-23T11:48:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="verifyTotalTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:practise.AppiumFramework.ECommerceTestCase_4@65e2dbf3]" name="verifyTotalTest" duration-ms="7" started-at="2020-10-23T11:48:23Z" finished-at="2020-10-23T11:48:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[SC/OMS/VerifyOrder]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1000]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[20000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at practise.AppiumFramework.ECommerceTestCase_4.verifyTotalTest(ECommerceTestCase_4.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTotalTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:practise.AppiumFramework.ECommerceTestCase_4@65e2dbf3]" name="tearDown" is-config="true" duration-ms="60" started-at="2020-10-23T11:48:23Z" finished-at="2020-10-23T11:48:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- practise.AppiumFramework.ECommerceTestCase_4 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
